"""update permissions list

Revision ID: 0421fc595310
Revises: c9eaa6dee1f7
Create Date: 2025-10-02 14:31:40.195868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0421fc595310'
down_revision: Union[str, Sequence[str], None] = 'c9eaa6dee1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('read_order', 'create_order', 'edit_order', 'delete_order', 'read_admin', 'issue_new_admin', 'edit_admin', 'delete_admin', 'issue_new_permission', 'read_other_permission', 'edit_permission', 'revoked_permission', name='permission_type', create_constraint=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_type',
               existing_type=sa.Enum('read_order', 'create_order', 'edit_order', 'delete_order', 'read_admin', 'issue_new_admin', 'edit_admin', 'delete_admin', 'issue_new_permission', 'read_other_permission', 'edit_permission', 'revoked_permission', name='permission_type', create_constraint=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
