"""unique username for admin

Revision ID: 35bea96d9ea6
Revises: d491ec9f444f
Create Date: 2025-09-26 15:32:39.547138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35bea96d9ea6"
down_revision: Union[str, Sequence[str], None] = "d491ec9f444f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_admins_user_name", ["user_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.drop_constraint("uq_admins_user_name", type_="unique")
    # ### end Alembic commands ###
