"""from description til comment migration

Revision ID: 699ee0dcc39e
Revises: 94114a49e8f0
Create Date: 2025-09-03 22:10:16.394428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699ee0dcc39e'
down_revision: Union[str, Sequence[str], None] = '94114a49e8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=100), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
