"""Delete permission_id for admins

Revision ID: 711d9eea31b5
Revises: 0421fc595310
Create Date: 2025-10-02 14:32:36.502184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711d9eea31b5'
down_revision: Union[str, Sequence[str], None] = '0421fc595310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('permission_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
