"""order relation with admins

Revision ID: 77f5b159663a
Revises: 82acb87edec0
Create Date: 2025-09-02 12:36:03.502305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f5b159663a'
down_revision: Union[str, Sequence[str], None] = '82acb87edec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_orders_admins', 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_admins', type_='foreignkey')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
