"""delete unused field and renaming some fields

Revision ID: 94114a49e8f0
Revises: 77f5b159663a
Create Date: 2025-09-03 10:58:37.223694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94114a49e8f0'
down_revision: Union[str, Sequence[str], None] = '77f5b159663a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jar_id', sa.String(length=100), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_orders_admins'), type_='foreignkey')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('signature')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('signature', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_admins'), 'admins', ['admin_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('jar_id')

    # ### end Alembic commands ###
