"""adding time of mono jars payment

Revision ID: ad0d5a3d6c94
Revises: c45902405538
Create Date: 2025-09-04 12:49:27.076825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0d5a3d6c94'
down_revision: Union[str, Sequence[str], None] = 'c45902405538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymenthistorys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymenthistorys', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
