"""permission table init

Revision ID: c9eaa6dee1f7
Revises: 35bea96d9ea6
Create Date: 2025-09-26 15:34:49.956832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9eaa6dee1f7'
down_revision: Union[str, Sequence[str], None] = '35bea96d9ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_type', sa.Enum('read_order', 'create_order', 'edit_order', 'delete_order', 'read_admin', 'issue_new_admin', 'edit_admin', 'delete_admin', 'issue_new_permission', 'edit_permission', 'revoked_permission', name='permission_type', create_constraint=True), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
